import torch
import torch.nn as nn
import torch.nn.functional as F
from torch import Tensor
from torch.nn.init import constant_, xavier_normal_, xavier_uniform_
from torch.nn.parameter import Parameter
from torch.nn.modules.linear import NonDynamicallyQuantizableLinear
from typing import Optional


class MultiHeadAttention(nn.Module):
    """
    Computes multi-head attention on batch-first jagged nested tensors.

    Sequence validity is encoded by the nested tensor layout, so this module
    does not rely on padding tokens or ``key_padding_mask`` inputs.
    """
    def __init__(
        self,
        embed_dim,
        num_heads,
        dropout=0.0,
        bias=True,
        add_bias_kv=False,
        add_zero_attn=False,
        kdim=None,
        vdim=None,
        pos_embeddings: Optional[nn.Module] = None,
        device=None,
        dtype=None,
    ) -> None:
        """Create a multi-head attention module for nested tensors.

        Args:
            embed_dim: Feature width of the query output space.
            num_heads: Number of attention heads.
            dropout: Dropout probability applied inside SDPA.
            bias: Whether projections use bias terms.
            add_bias_kv: Whether to append learned key and value bias tokens.
            add_zero_attn: Whether to append a zero-attention slot.
            kdim: Optional input width for keys.
            vdim: Optional input width for values.
            pos_embeddings: Optional positional embedding module applied to
                queries and keys.
            device: Optional device passed to module parameters.
            dtype: Optional dtype passed to module parameters.

        Returns:
            None.
        """
        factory_kwargs = {"device": device, "dtype": dtype}
        super().__init__()
        self.embed_dim = embed_dim
        self.kdim = kdim if kdim is not None else embed_dim
        self.vdim = vdim if vdim is not None else embed_dim
        self._qkv_same_embed_dim = self.kdim == embed_dim and self.vdim == embed_dim
        
        self.num_heads = num_heads
        self.dropout = dropout
        self.head_dim = embed_dim // num_heads
        assert (
            self.head_dim * num_heads == self.embed_dim
        ), "embed_dim must be divisible by num_heads"

        if not self._qkv_same_embed_dim:
            self.q_proj_weight = Parameter(
                torch.empty((embed_dim, embed_dim), **factory_kwargs)
            )
            self.k_proj_weight = Parameter(
                torch.empty((embed_dim, self.kdim), **factory_kwargs)
            )
            self.v_proj_weight = Parameter(
                torch.empty((embed_dim, self.vdim), **factory_kwargs)
            )
            self.register_parameter("in_proj_weight", None)
        else:
            self.in_proj_weight = Parameter(
                torch.empty((3 * embed_dim, embed_dim), **factory_kwargs)
            )
            self.register_parameter("q_proj_weight", None)
            self.register_parameter("k_proj_weight", None)
            self.register_parameter("v_proj_weight", None)

        if bias:
            self.in_proj_bias = Parameter(torch.empty(3 * embed_dim, **factory_kwargs))
        else:
            self.register_parameter("in_proj_bias", None)
        self.out_proj = NonDynamicallyQuantizableLinear(
            embed_dim, embed_dim, bias=bias, **factory_kwargs
        )

        if add_bias_kv:
            self.bias_k = Parameter(torch.empty((1, embed_dim), **factory_kwargs))
            self.bias_v = Parameter(torch.empty((1, embed_dim), **factory_kwargs))
        else:
            self.bias_k = self.bias_v = None

        self.add_zero_attn = add_zero_attn

        self.pos_embeddings = pos_embeddings

        self._reset_parameters()

    def _reset_parameters(self):
        """Initialize projection parameters."""
        if self._qkv_same_embed_dim:
            xavier_uniform_(self.in_proj_weight)
        else:
            xavier_uniform_(self.q_proj_weight)
            xavier_uniform_(self.k_proj_weight)
            xavier_uniform_(self.v_proj_weight)

        if self.in_proj_bias is not None:
            constant_(self.in_proj_bias, 0.0)
            constant_(self.out_proj.bias, 0.0)
        if self.bias_k is not None:
            xavier_normal_(self.bias_k)
        if self.bias_v is not None:
            xavier_normal_(self.bias_v)

    def __setstate__(self, state):
        """Load legacy checkpoints that predate ``_qkv_same_embed_dim``."""
        # Support loading old MultiheadAttention checkpoints generated by v1.1.0
        if "_qkv_same_embed_dim" not in state:
            state["_qkv_same_embed_dim"] = True

        super().__setstate__(state)

    def forward(
        self, 
        query: torch.Tensor, 
        key: torch.Tensor, 
        value: torch.Tensor, 
        attn_mask: Optional[Tensor] = None,
        query_input_pos: Optional[torch.Tensor] = None,
        key_input_pos: Optional[torch.Tensor] = None,
        is_causal: bool = False,
    ) -> torch.Tensor:
        """
        Forward pass; runs the following process:
            1. Apply input projection
            2. Split heads and prepare for SDPA
            3. Run SDPA
            4. Apply output projection

        Args:
            query (torch.Tensor): Query nested tensor of shape
                ``[batch, q_len, embed_dim]``.
            key (torch.Tensor): Key nested tensor of shape
                ``[batch, kv_len, kdim]``.
            value (torch.Tensor): Value nested tensor of shape
                ``[batch, kv_len, vdim]``.
            attn_mask (torch.Tensor, optional): Optional attention mask passed
                into scaled dot-product attention. The current nested-tensor
                path expects this to be ``None``.
            query_input_pos (torch.Tensor, optional): Optional nested position
                ids aligned with ``query`` for positional embeddings.
            key_input_pos (torch.Tensor, optional): Optional nested position ids
                aligned with ``key`` for positional embeddings.
            is_causal (bool, optional): Whether to apply a causal attention
                pattern. Default: ``False``.

        Returns:
            torch.Tensor: Attention output nested tensor with shape
                ``[batch, q_len, embed_dim]``.
        """
        assert attn_mask is None

        # Step 1. Apply input projection
        if self._qkv_same_embed_dim:
            if query is key and key is value:
                result = F.linear(query, self.in_proj_weight, self.in_proj_bias)
                q, k, v = torch.chunk(result, 3, dim=-1)
            else:
                q_weight, k_weight, v_weight = torch.chunk(self.in_proj_weight, 3, dim=0)
                if self.in_proj_bias is not None:
                    q_bias, k_bias, v_bias = torch.chunk(self.in_proj_bias, 3, dim=0)
                else:
                    q_bias, k_bias, v_bias = None, None, None
                q, k, v = F.linear(query, q_weight, q_bias), F.linear(key, k_weight, k_bias), F.linear(value, v_weight, v_bias)
        else:
            if self.in_proj_bias is not None:
                q_bias, k_bias, v_bias = torch.chunk(self.in_proj_bias, 3, dim=0)
            else:
                q_bias, k_bias, v_bias = None, None, None
            q = F.linear(query, self.q_proj_weight, q_bias)
            k = F.linear(query, self.k_proj_weight, k_bias)
            v = F.linear(query, self.v_proj_weight, v_bias)

        # Step 2. Split heads and prepare for SDPA
        # reshape q, k, v to separate by head
        # (N, L_t, E_total) -> (N, L_t, nheads, E_head)
        q = q.unflatten(-1, [self.num_heads, self.head_dim])
        # (N, L_s, E_total) -> (N, L_s, nheads, E_head)
        k = k.unflatten(-1, [self.num_heads, self.head_dim])
        # (N, L_s, E_total) -> (N, L_s, nheads, E_head)
        v = v.unflatten(-1, [self.num_heads, self.head_dim])

        if self.pos_embeddings is not None:
            q = self.pos_embeddings(q, query_input_pos)
            k = self.pos_embeddings(k, key_input_pos)

        if self.bias_k is not None and self.bias_v is not None:
            k = torch.nested.as_nested_tensor(
                [torch.cat([ki, self.bias_k.unflatten(-1, [self.num_heads, self.head_dim])]) for ki in k.unbind()],
                layout=torch.jagged
            )
            v = torch.nested.as_nested_tensor(
                [torch.cat([vi, self.bias_v.unflatten(-1, [self.num_heads, self.head_dim])]) for vi in v.unbind()],
                layout=torch.jagged
            )
        else:
            assert self.bias_k is None
            assert self.bias_v is None

        # add zero attention along batch dimension (now first)
        if self.add_zero_attn:
            zero_attn_shape = (1, self.num_heads, self.head_dim)
            k = torch.nested.as_nested_tensor(
                [torch.cat([ki, torch.zeros(zero_attn_shape, dtype=ki.dtype, device=ki.device)], dim=0)
                 for ki in k.unbind()],
                layout=torch.jagged
            )
            v = torch.nested.as_nested_tensor(
                [torch.cat([vi, torch.zeros(zero_attn_shape, dtype=vi.dtype, device=vi.device)], dim=0)
                 for vi in v.unbind()],
                layout=torch.jagged
            )

        # (N, L_t, nheads, E_head) -> (N, nheads, L_t, E_head)
        q = q.transpose(1, 2)
        # (N, L_s, nheads, E_head) -> (N, nheads, L_s, E_head)
        k = k.transpose(1, 2)
        # (N, L_s, nheads, E_head) -> (N, nheads, L_s, E_head)
        v = v.transpose(1, 2)

        # Step 3. Run SDPA
        # (N, nheads, L_t, E_head)
        attn_output = F.scaled_dot_product_attention(
            q, k, v, attn_mask=attn_mask, dropout_p=self.dropout, is_causal=is_causal)
        # (N, nheads, L_t, E_head) -> (N, L_t, nheads, E_head) -> (N, L_t, E_total)
        attn_output = attn_output.transpose(1, 2).flatten(-2)

        # Step 4. Apply output projection
        # (N, L_t, E_total) -> (N, L_t, E_out)
        attn_output = self.out_proj(attn_output)

        return attn_output
